baseURL = 'http://t3hami.github.io/'
languageCode = 'en-us'
title = "Tehami's Blog"
theme = 'PaperMod'

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "Tech"
    url = "/tech/"
    weight = 1

  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[params]
  env = "production"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  mainSections = ["tech", "books"]
  ShowPostOnHome = true

  # Profile section
  [params.homeInfoParams]
    Title = "Muhammad Tehami"
    Content = "DevOps & Cloud Engineer at Nisum Technologies Inc. | Experienced in Linux, Kubernetes, Terraform, and cloud platforms. Passionate about automation, performance optimization, and building scalable systems. Also writes about technology, productivity, book reviews, and travel experiences."

  # Social links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/t3hami"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/t3hami"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/MuhammadTehami"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:t3hami [at] gmail [dot] com"

# Author info (for meta tags etc.)
[params.author]
  name = "Muhammad Tehami"
  email = "t3hami [at] gmail [dot] com"

[markup.goldmark.renderer]
  unsafe = true
